yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('group/<slug>/', views.group_posts, name='group')
]

yatube/yatube/urls.py
from django.contrib import admin
# Функция include позволит использовать path() из других файлов.
# Импортируем!
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import CharField

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> CharField:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name='posts',
        blank=True,
        null=True
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
# Импортируем модель, чтобы обратиться к ней
from .models import Post, Group



# Главная страница
def index(request):
    title = 'Yatube - соцсеть для разработчиков'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
        'title': title,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:10]
    title = 'Гроуп-пост - еее бой'
    context = {
        'group': group,
        'posts': posts,
        'title': title,
    }
    return render(request, 'posts/group_list.html', context)

# view-функция принимает параметр slug из path()

yatube/templates/base.html
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      <div>
        {% block content %}
        Контент не подвезли :(
        {% endblock %}
      </div>
    </main>
      {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
   {% load static %}
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>

yatube/templates/includes/header.html
    {% load static %}
     <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href={% url 'posts:index' %}>
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
Лев Толстой – зеркало русской революции.
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{group}}</h1>
    <p>{{group.description}}</p>
      <article>
        {% for post in posts %}
        <ul>
            <li>
                Автор: {{post.autor.get_full_name}}
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y"}}
        </ul>
        <p>{{post.text}}</p>
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
    </article>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
 <title>
   {% block title %}
   {% endblock %}
 </title>
 <body>
   <header>
     {% include 'includes/header.html' %}
   </header>
   {% block content %}
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>Последние обновления на сайте</h1>
        <article>
        {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        </article>
        <!-- под последним постом нет линии -->
      </div>
    </main>
 {% endblock %}